"""create pcr schema

Revision ID: dc50b0035fa9
Revises:
Create Date: 2026-09-23 01:05:21.605598

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc50b0035fa9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval_route",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("route_code", sa.Unicode(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Unicode(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_route")),
        sa.UniqueConstraint("route_code", "version", name=op.f("uq_approval_route_route_code")),
    )
    with op.batch_alter_table("approval_route", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_approval_route_route_code"), ["route_code"], unique=False
        )

    op.create_table(
        "pcr",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pcr_code", sa.Unicode(length=30), nullable=False),
        sa.Column("policy_code", sa.Unicode(length=50), nullable=False),
        sa.Column("status", sa.Unicode(length=30), nullable=False),
        sa.Column("supersedes_pcr_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Unicode(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["supersedes_pcr_id"], ["pcr.id"], name=op.f("fk_pcr_supersedes_pcr_id_pcr")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pcr")),
        sa.UniqueConstraint("pcr_code", name=op.f("uq_pcr_pcr_code")),
    )
    with op.batch_alter_table("pcr", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pcr_policy_code"), ["policy_code"], unique=False)
        batch_op.create_index(batch_op.f("ix_pcr_status"), ["status"], unique=False)

    op.create_table(
        "approval_stage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("mode", sa.Unicode(length=20), nullable=False),
        sa.Column("allow_same_approver_multiple_requirements", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["approval_route.id"],
            name=op.f("fk_approval_stage_route_id_approval_route"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_stage")),
    )
    with op.batch_alter_table("approval_stage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approval_stage_route_id"), ["route_id"], unique=False)

    op.create_table(
        "pcr_revision",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pcr_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Unicode(length=200), nullable=False),
        sa.Column("description", sa.UnicodeText(), nullable=False),
        sa.Column("change_type", sa.Unicode(length=50), nullable=False),
        sa.Column("rationale", sa.UnicodeText(), nullable=False),
        sa.Column("current_policy", sa.UnicodeText(), nullable=False),
        sa.Column("proposed_policy", sa.UnicodeText(), nullable=False),
        sa.Column("affected_policy_sections", sa.JSON(), nullable=False),
        sa.Column("impact_summary", sa.UnicodeText(), nullable=False),
        sa.Column("technical_change_required", sa.Boolean(), nullable=False),
        sa.Column("technical_change_details", sa.UnicodeText(), nullable=True),
        sa.Column("communication_targets", sa.JSON(), nullable=False),
        sa.Column("implementation_date", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Unicode(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["pcr_id"], ["pcr.id"], name=op.f("fk_pcr_revision_pcr_id_pcr")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pcr_revision")),
        sa.UniqueConstraint("pcr_id", "revision_number", name=op.f("uq_pcr_revision_pcr_id")),
    )
    with op.batch_alter_table("pcr_revision", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pcr_revision_pcr_id"), ["pcr_id"], unique=False)

    op.create_table(
        "approval_requirement",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stage_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=False),
        sa.Column("selector_type", sa.Unicode(length=30), nullable=False),
        sa.Column("selector_value", sa.Unicode(length=255), nullable=False),
        sa.Column("min_approvals", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["approval_stage.id"],
            name=op.f("fk_approval_requirement_stage_id_approval_stage"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_requirement")),
    )
    with op.batch_alter_table("approval_requirement", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_approval_requirement_stage_id"), ["stage_id"], unique=False
        )

    op.create_table(
        "approval_workflow",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pcr_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.Column("route_code", sa.Unicode(length=100), nullable=False),
        sa.Column("route_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.Unicode(length=30), nullable=False),
        sa.Column("created_by", sa.Unicode(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pcr_id"], ["pcr.id"], name=op.f("fk_approval_workflow_pcr_id_pcr")
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["pcr_revision.id"],
            name=op.f("fk_approval_workflow_revision_id_pcr_revision"),
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["approval_route.id"],
            name=op.f("fk_approval_workflow_route_id_approval_route"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_workflow")),
    )
    with op.batch_alter_table("approval_workflow", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approval_workflow_pcr_id"), ["pcr_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_approval_workflow_revision_id"), ["revision_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_approval_workflow_status"), ["status"], unique=False)

    op.create_table(
        "audit_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pcr_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.Unicode(length=100), nullable=False),
        sa.Column("actor", sa.Unicode(length=255), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["pcr_id"], ["pcr.id"], name=op.f("fk_audit_event_pcr_id_pcr")),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["pcr_revision.id"],
            name=op.f("fk_audit_event_revision_id_pcr_revision"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_event_event_type"), ["event_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_event_pcr_id"), ["pcr_id"], unique=False)

    op.create_table(
        "approval_decision",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("stage_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=True),
        sa.Column("decision_type", sa.Unicode(length=30), nullable=False),
        sa.Column("actor", sa.Unicode(length=255), nullable=False),
        sa.Column("comment", sa.UnicodeText(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["approval_requirement.id"],
            name=op.f("fk_approval_decision_requirement_id_approval_requirement"),
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["approval_stage.id"],
            name=op.f("fk_approval_decision_stage_id_approval_stage"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["approval_workflow.id"],
            name=op.f("fk_approval_decision_workflow_id_approval_workflow"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_decision")),
        sa.UniqueConstraint(
            "workflow_id", "stage_id", "actor", name=op.f("uq_approval_decision_workflow_id")
        ),
    )
    with op.batch_alter_table("approval_decision", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_approval_decision_workflow_id"), ["workflow_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approval_decision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_decision_workflow_id"))

    op.drop_table("approval_decision")
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_event_pcr_id"))
        batch_op.drop_index(batch_op.f("ix_audit_event_event_type"))

    op.drop_table("audit_event")
    with op.batch_alter_table("approval_workflow", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_workflow_status"))
        batch_op.drop_index(batch_op.f("ix_approval_workflow_revision_id"))
        batch_op.drop_index(batch_op.f("ix_approval_workflow_pcr_id"))

    op.drop_table("approval_workflow")
    with op.batch_alter_table("approval_requirement", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_requirement_stage_id"))

    op.drop_table("approval_requirement")
    with op.batch_alter_table("pcr_revision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pcr_revision_pcr_id"))

    op.drop_table("pcr_revision")
    with op.batch_alter_table("approval_stage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_stage_route_id"))

    op.drop_table("approval_stage")
    with op.batch_alter_table("pcr", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pcr_status"))
        batch_op.drop_index(batch_op.f("ix_pcr_policy_code"))

    op.drop_table("pcr")
    with op.batch_alter_table("approval_route", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_route_route_code"))

    op.drop_table("approval_route")
    # ### end Alembic commands ###
