from typing import Protocol
from uuid import UUID

from pcr_governance_app.domain.approval import ApprovalRoute, ApprovalWorkflow
from pcr_governance_app.domain.audit import AuditEvent
from pcr_governance_app.domain.pcr import PCR


class PCRRepository(Protocol):
    def add(self, pcr: PCR) -> None: ...

    def get(self, pcr_id: UUID) -> PCR | None: ...

    def get_by_code(self, pcr_code: str) -> PCR | None: ...

    def list_all(self) -> list[PCR]: ...

    def save(self, pcr: PCR) -> None: ...


class AuditEventRepository(Protocol):
    def add(self, event: AuditEvent) -> None: ...

    def list_for_pcr(self, pcr_id: UUID) -> list[AuditEvent]: ...


class ApprovalRouteRepository(Protocol):
    def add(self, route: ApprovalRoute) -> None: ...

    def get(self, route_id: UUID) -> ApprovalRoute | None: ...

    def get_active_by_code(self, route_code: str) -> ApprovalRoute | None: ...

    def list_active(self) -> list[ApprovalRoute]: ...


class ApprovalWorkflowRepository(Protocol):
    def add(self, workflow: ApprovalWorkflow) -> None: ...

    def get(self, workflow_id: UUID) -> ApprovalWorkflow | None: ...

    def get_active_for_pcr(self, pcr_id: UUID) -> ApprovalWorkflow | None: ...

    def save(self, workflow: ApprovalWorkflow) -> None: ...
